### ISSUE TITLE
Xenia and PCSX2 Support

### ISSUE THREAD

**Issue by quinton-ashley** [quinton-ashley/bottlenose#1]
In order to support the Xenia and PCSX2 emulators I need a database files for xbox360 and ps2 games. gametdb does not have xbox 360 or PS2 game database files availabe. If someone could scrape a database site for me and give me a database file then I could support these emulators.

**Comment by vassilmladenov** [comment]
Is this issue still open? I found this: https://psxdatacenter.com/psx2/ntsc-u_list2.html, should be a trivial transformation to your preferred schema. I can take a look at it later. Is there a development guide somewhere?

**Comment by quinton-ashley** [comment]
yup! Just finished it.  Sorry I should've closed the issue.  I went with discs as separate games so that disc x can be found by searching the database files. If, for example, I added them as an array to the disc 1 of the game I wouldn't be able to do that.  I only store a reference to the first disc of a game, assuming the other disc(s) are only for install in most cases.
