### ISSUE TITLE
Icon redesign suggestions

### ISSUE THREAD

**Issue by iiiGerardoiii** [quinton-ashley/bottlenose#4]
Are you open to suggestions? I made these, what do you think:
![bottlenoseideas](https://user-images.githubusercontent.com/6264194/51701869-fe83f000-1fd7-11e9-8fd8-e967dfa7ed43.jpg)
If you're interested in any of these I could give you the vector file, or do some changes.

**Comment by quinton-ashley** [comment]
Sorry, I can tell you put some work into these but I'm not open to suggestions with the new Bottlenose logo which is here to stay.

If you want to know what I think anyway, I think they're too simple to be visually appealing at large dimensions and details like the fins are not pronounced enough to look good at icon size.  The combed edges are too small at icon size as well.  There's too much negative space, the dolphin should be the largest element visually.  I don't like that the dolphin goes outside the circle but that's more of a personal preference.
