### ISSUE TITLE
Some Donation UI Buttons Are Broken

### ISSUE THREAD

**Issue by legoboy0109** [quinton-ashley/bottlenose#5]
After Clicking on the "I already donated button, trying to press the "I haven't Donated Yet" button does not work. Also, after clicking on the continue button with an incorrect key, the "Okay" button is also broken. 
![Button1](https://user-images.githubusercontent.com/15899271/59287435-e3381b00-8c2e-11e9-8d3d-78e477336c47.png)
![image](https://user-images.githubusercontent.com/15899271/59287483-f945db80-8c2e-11e9-840d-405d295af764.png)

**Comment by quinton-ashley** [comment]
Thanks for letting me know, I will fix this in the next version.

**Comment by quinton-ashley** [comment]
Fixed in v1.2.0
