### ISSUE TITLE
Size of readme

### ISSUE THREAD

**Issue by slx7R4GDZM** [quinton-ashley/bottlenose#8]
This page takes quite a while to load on a slower connection.
The readme is nearly 40MB due to the images while most readmes on GitHub are at or under 1MB.

**Comment by quinton-ashley** [comment]
Thanks for bringing this to my attention.  I made all the LQ preview images half size and used pngquant to compress them.  They're 4.5MB in total now.  Don't know about the full readme total.

**Comment by quinton-ashley** [comment]
I also added this warning to the readme:

Warning!  If you pay for internet by bandwidth be aware that for large game libraries Bottlenose will download a lot of image files and this will take a lot of bandwidth.
